VERY_LOW  = -2
MODERATE  = -1
NORMAL    =  0
HIGH      =  1
EMERGENCY =  2

levels = {
    'VERY_LOW': VERY_LOW,
    'MODERATE': MODERATE,
    'NORMAL': NORMAL,
    'HIGH': HIGH,
    'EMERGENCY': EMERGENCY
    }
